# Generated by Django 3.2.8 on 2022-02-07 15:11
from datetime import datetime

from django.db import migrations


def initial_data(apps, schema_editor):
    user_model = apps.get_model("api_todo", "User")
    note_model = apps.get_model("api_todo", "Note")

    user1 = user_model(username='giabao', password='2807')
    user2 = user_model(username='baobao', password='1234')

    user1.save()
    user2.save()

    note1 = note_model(note='do something', deadline=datetime(2022, 2, 10), something='hehehe', user=user1)
    note2 = note_model(note='coding abc', deadline=datetime(2022, 2, 14), something='trust kidding', user=user1)

    note1.save()
    note2.save()


def delete_data(apps, schema_editor):
    user_model = apps.get_model("api_todo", "User")
    note_model = apps.get_model("api_todo", "Note")

    user_model.objects.all().delete()
    note_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_todo', '0003_note'),
    ]

    operations = [
        migrations.RunPython(initial_data, delete_data)
    ]
